### ISSUE TITLE
Fejl i behandling af NotifyValidatedMeasureData: 500 Internal Server Error

### ISSUE THREAD

**Issue by jli-energinet** [Energinet-DataHub/green-energy-hub#271]
INC0285747
JLI

Vi har fået en sag fra en it-leverandør, som forsøger at indsende en NotifyValidatedMeasureData.

De får en 500 – Internal Server Error, når de forsøger at sende vedhæftede XML.

[https://app.zenhub.com/files/349352719/ea8b6d42-f911-4d27-bd82-2a7f77d2339f/download](https://app.zenhub.com/files/349352719/ea8b6d42-f911-4d27-bd82-2a7f77d2339f/download)

**Comment by MadsBloendAndersen** [comment]
@jli-energinet The issue is not the schema related, although they might need to revisit it. I suggest that Christian Odgaard could provide the correct schema, or forward the message that i have written in an earlier comment, to the actor. This will not solve this specific incident, but will maybe prevent future issues being created. 

As for this specific issue.

We have given the incident to @mknic (Mighty ducks) because we believe that it is an environment/platform issue.

**Comment by mknic** [comment]
@MadsBloendAndersen @jli-energinet we will look into this on Friday and update the issue with our findings.

**Comment by jli-energinet** [comment]
@mknic: Any updates on this issue?

**Comment by mknic** [comment]
@jli-energinet it has been solved and is verified in `b-002` (aktørtestmiljøet)

**Comment by jli-energinet** [comment]
Market party has confirmed that issue is resolved
